name: NMRF
channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - abseil-cpp=20211102.0
  - absl-py=2.1.0
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - charset-normalizer=2.0.4
  - cuda-cudart=11.7.99
  - cuda-cupti=11.7.101
  - cuda-libraries=11.7.1
  - cuda-nvrtc=11.7.99
  - cuda-nvtx=11.7.91
  - cuda-runtime=11.7.1
  - ffmpeg=4.3
  - freetype=2.12.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - grpc-cpp=1.48.2
  - grpcio=1.48.2
  - idna=3.4
  - importlib-metadata=7.0.2
  - intel-openmp=2023.1.0
  - jpeg=9e
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libcublas=11.10.3.66
  - libcufft=10.7.2.124
  - libcufile=1.9.0.20
  - libcurand=10.3.5.119
  - libcusolver=11.4.0.1
  - libcusparse=11.7.4.91
  - libdeflate=1.17
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.4
  - libnpp=11.7.4.75
  - libnvjpeg=11.8.0.2
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - markdown=3.6
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - ncurses=6.4
  - nettle=3.7.3
  - numpy=1.24.3
  - numpy-base=1.24.3
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.13
  - pillow=10.2.0
  - pip=23.3.1
  - protobuf=3.20.3
  - python=3.8.18
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - pytorch-mutex=1.0
  - re2=2022.04.01
  - readline=8.2
  - requests=2.31.0
  - setuptools=68.2.2
  - six=1.16.0
  - sqlite=3.41.2
  - tbb=2021.8.0
  - tensorboard=2.16.2
  - tensorboard-data-server=0.7.0
  - tk=8.6.12
  - torchvision=0.14.0
  - typing_extensions=4.9.0
  - urllib3=2.1.0
  - werkzeug=2.1.2
  - wheel=0.41.2
  - xz=5.4.6
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - antlr4-python3-runtime==4.9.3
    - contourpy==1.1.1
    - cycler==0.12.1
    - einops==0.7.0
    - filelock==3.13.1
    - fonttools==4.50.0
    - fsspec==2024.3.0
    - huggingface-hub==0.21.4
    - imageio==2.34.0
    - importlib-resources==6.3.1
    - kiwisolver==1.4.5
    - matplotlib==3.7.5
    - omegaconf==2.3.0
    - opencv-python==4.9.0.80
    - packaging==24.0
    - pyparsing==3.1.2
    - python-dateutil==2.9.0.post0
    - pyyaml==6.0.1
    - safetensors==0.4.2
    - tabulate==0.9.0
    - termcolor==2.4.0
    - timm==0.9.16
    - tqdm==4.66.2
    - yacs==0.1.8
