SOLVER:
  NO_RESUME_OPTIMIZER: True
  IMS_PER_BATCH: 4
  MAX_ITER: 30000
  BASE_LR: 0.0002
  CHECKPOINT_PERIOD: 10000
  MAX_DISP: 384
  LOSS_TYPE: "SMOOTH_L1"
DATASETS:
  TRAIN: ("kitti_mix_2012_train",)
  CROP_SIZE: [304, 1152]
  TEST: ("kitti_2012_val",)
TEST:
  EVAL_PERIOD: 500
  EVAL_MAX_DISP: [null]