SOLVER:
  NO_RESUME_OPTIMIZER: True
  IMS_PER_BATCH: 4
  MAX_ITER: 39000
  BASE_LR: 0.0002
  CHECKPOINT_PERIOD: 10000
  MAX_DISP: 384
  LOSS_TYPE: "SMOOTH_L1"
DATASETS:
  TRAIN: ("kitti_mix",)
  CROP_SIZE: [288, 1152]
  DIVIS_BY: 32
  TEST: ("kitti_2015_val",)
TEST:
  EVAL_PERIOD: 500
  EVAL_MAX_DISP: [null]
BACKBONE:
  MODEL_TYPE: "swin"
  OUT_CHANNELS: 128
  DROP_PATH: 0.4
  COMPAT: False